flowchart TD
  home["Home"]
  messages["Messages"]
  profile["Profile"]
  biometricLogin["Biometric Login"]
  familyCarer["Family Carer Screen"]
  familyCarer_addCaredFor["Family Carer Add Cared For Screen"]
  familyCarer_addTrusted["Family Carer Add Trusted Screen"]
  familyCarer_caredFor["Family Carer Person Detail Screen"]
  familyCarer_caredFor_confirm["Family Carer Switch Confirm Screen"]
  familyCarer_trusted["Family Carer Trusted Person Detail Screen"]
  familyCarer_trusted_remove["Family Carer Remove Trusted Person Screen"]
  familyCarer_trusted_reason["Family Carer Removal Reason Screen"]
  familyCarer_trusted_confirm["Family Carer Removal Confirm Screen"]
  familyCarer_trusted_success["Family Carer Removal Success Screen"]
  prescriptions2["Prescriptions"]
  appointments["Appointments"]
  referrals["Referrals"]
  cervicalScreeningDetail["Cervical Screening Detail"]
  bookAppointmentMenu["Book Appointment Menu"]
  askHealthProblemStart["Ask Health Problem Start"]
  bookAppointmentStart["Book Appointment Start"]
  noAppointmentsAvailable["No Appointments Available"]
  prescriptionStartRepeat["Prescription Start Repeat"]
  checkPrescriptions["Check Prescriptions Progress"]
  prescriptionAddPharmacy["Prescription Add Pharmacy"]
  prescriptionMedicineDetail["Prescription Medicine Detail"]
  prescriptionConfirmationRepeat["Prescription Confirmation Repeat"]
  prescriptionAdditionalDetail["Prescription Additional Detail"]
  prescriptionFormRepeat["Prescription Form Repeat"]
  message_detail["Message Detail"]
  archived_messages["Archived Messages"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_check_the_pharmacy["Check your chosen pharmacy - NHS App prototype"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_and_past_medicines["Medicines record - NHS App prototype"]
  https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App["Emergency prescriptions - NHS 111"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_start["Choose a pharmacy - NHS App prototype"]
  https___www_nhs_uk_conditions_cervical_screening["Cervical screening - NHS"]
  https___111_nhs_uk_["Get help for your symptoms - NHS 111"]
  https___nhsapp_native_test_6c35b83d719e_herokuapp_com_pages_integrations_patchs["Patchs - Online Consultation"]
  https___nhsapp_native_test_6c35b83d719e_herokuapp_com_pages_services_gp_appointment_type["Select an appointment type - NHS App prototype"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_requested_medicines["Check if your GP has approved a request - NHS App prototype"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_approved_prescriptions["Check prescriptions with the pharmacy - NHS App prototype"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_start_mode_change["Change your pharmacy - NHS App prototype"]
  https___www_nhs_uk_tests_and_treatments["Tests and treatments A to Z - NHS"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_select_medicines["Choose the medicines you need - NHS App prototype"]
  https___111_nhs_uk_triage_check_its_not_an_emergency_journeyType_EmergencyPrescription["Call 999 now for any of these: - NHS 111"]
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening["What is cervical screening? - NHS"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_one_off_medicines["One-off medicines - NHS App prototype"]
  https___111_nhs_uk_Help_OtherWays_journeyType_EmergencyPrescription["Other ways to contact 111 - NHS 111"]
  https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done["Why cervical screening is done - NHS"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_repeat_medicines["Current repeat medicines - NHS App prototype"]
  https___111_nhs_uk_Help_Terms["Terms and conditions - NHS 111"]
  https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited["When you'll be invited for cervical screening - NHS"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_past_repeat_medicines["Past repeat medicines - NHS App prototype"]
  https___111_nhs_uk_Help_Cookies["Cookies on 111.nhs.uk - NHS 111"]
  https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book["How to book cervical screening - NHS"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_pharmacy_type["Choose a type of pharmacy - NHS App prototype"]
  https___111_nhs_uk_Help_Privacy["Privacy statement - NHS 111"]
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens["What happens at your cervical screening appointment - NHS"]
  https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results["Your cervical screening results - NHS"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_prescription["Your prescription - NHS App prototype"]
  https___111_nhs_uk_Help_Accessibility["Accessibility Statement - NHS 111"]
  https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support["Further help and support for cervical screening - NHS"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_past_prescriptions["Past prescriptions - NHS App prototype"]
  https___111_nhs_uk_triage_check_your_symptoms["Check your symptoms - NHS 111"]
  https___www_nhs_uk_health_a_to_z["Health A to Z - NHS"]
  https___111_nhs_uk_guided_entry_dental_help["Get dental help - NHS 111"]
  https___www_nhs_uk_tests_and_treatments_abdominal_aortic_aneurysm_screening["Abdominal aortic aneurysm (AAA) screening - NHS"]
  https___111_nhs_uk_guided_entry_mental_health_help["Get mental health help - NHS 111"]
  https___www_nhs_uk_tests_and_treatments_abortion["Abortion - NHS"]
  https___111_nhs_uk_guided_entry_sexual_health_help["Get sexual health help - NHS 111"]
  https___www_nhs_uk_tests_and_treatments_acl_anterior_cruciate_ligament_surgery["ACL (anterior cruciate ligament) surgery - NHS"]

  home --> messages
  home --> profile
  home --> prescriptions2
  home --> appointments
  messages --> archived_messages
  messages --> message_detail
  profile --> familyCarer
  profile --> biometricLogin
  familyCarer --> familyCarer_caredFor
  familyCarer --> familyCarer_trusted
  familyCarer --> familyCarer_addCaredFor
  familyCarer --> familyCarer_addTrusted
  familyCarer_caredFor --> familyCarer_caredFor_confirm
  familyCarer_caredFor_confirm --> home
  familyCarer_trusted --> familyCarer_trusted_remove
  familyCarer_trusted_remove --> familyCarer_trusted_reason
  familyCarer_trusted_reason --> familyCarer_trusted_confirm
  familyCarer_trusted_confirm --> familyCarer_trusted_success
  prescriptions2 --> checkPrescriptions
  prescriptions2 --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_check_the_pharmacy
  prescriptions2 --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_and_past_medicines
  prescriptions2 --> https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App
  prescriptions2 --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_start
  appointments --> bookAppointmentMenu
  appointments --> referrals
  cervicalScreeningDetail --> https___www_nhs_uk_conditions_cervical_screening
  bookAppointmentMenu --> askHealthProblemStart
  bookAppointmentMenu --> bookAppointmentStart
  bookAppointmentMenu --> noAppointmentsAvailable
  askHealthProblemStart --> https___111_nhs_uk_
  askHealthProblemStart --> https___nhsapp_native_test_6c35b83d719e_herokuapp_com_pages_integrations_patchs
  bookAppointmentStart --> https___111_nhs_uk_
  bookAppointmentStart --> https___nhsapp_native_test_6c35b83d719e_herokuapp_com_pages_services_gp_appointment_type
  noAppointmentsAvailable --> askHealthProblemStart
  noAppointmentsAvailable --> https___111_nhs_uk_
  prescriptionStartRepeat --> prescriptionAddPharmacy
  prescriptionStartRepeat --> https___111_nhs_uk_
  checkPrescriptions --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_requested_medicines
  checkPrescriptions --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_approved_prescriptions
  prescriptionAddPharmacy --> prescriptionMedicineDetail
  prescriptionAddPharmacy --> prescriptions2
  prescriptionMedicineDetail --> prescriptionAdditionalDetail
  prescriptionMedicineDetail --> prescriptions2
  prescriptionConfirmationRepeat --> prescriptions2
  prescriptionAdditionalDetail --> prescriptionFormRepeat
  prescriptionAdditionalDetail --> prescriptions2
  prescriptionFormRepeat --> prescriptionConfirmationRepeat
  prescriptionFormRepeat --> prescriptions2
  archived_messages --> message_detail
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_check_the_pharmacy --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_start_mode_change
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_check_the_pharmacy --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_select_medicines
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_and_past_medicines --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_one_off_medicines
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_and_past_medicines --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_repeat_medicines
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_and_past_medicines --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_past_repeat_medicines
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_start --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_pharmacy_type
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_requested_medicines --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_approved_prescriptions
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_approved_prescriptions --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_prescription
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_approved_prescriptions --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_past_prescriptions
  https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App --> https___111_nhs_uk_
  https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App --> https___111_nhs_uk_triage_check_its_not_an_emergency_journeyType_EmergencyPrescription
  https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App --> https___111_nhs_uk_Help_OtherWays_journeyType_EmergencyPrescription
  https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App --> https___111_nhs_uk_Help_Terms
  https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App --> https___111_nhs_uk_Help_Cookies
  https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App --> https___111_nhs_uk_Help_Privacy
  https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App --> https___111_nhs_uk_Help_Accessibility
  https___111_nhs_uk_ --> https___111_nhs_uk_triage_check_your_symptoms
  https___111_nhs_uk_ --> https___111_nhs_uk_guided_entry_dental_help
  https___111_nhs_uk_ --> https___111_nhs_uk_guided_entry_mental_health_help
  https___111_nhs_uk_ --> https___111_nhs_uk_guided_entry_sexual_health_help
  https___111_nhs_uk_ --> https___111_nhs_uk_Help_Cookies
  https___111_nhs_uk_ --> https___111_nhs_uk_Help_Privacy
  https___111_nhs_uk_ --> https___111_nhs_uk_Help_Terms
  https___111_nhs_uk_ --> https___111_nhs_uk_Help_Accessibility
  https___www_nhs_uk_conditions_cervical_screening --> https___www_nhs_uk_tests_and_treatments
  https___www_nhs_uk_conditions_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening
  https___www_nhs_uk_conditions_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done
  https___www_nhs_uk_conditions_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited
  https___www_nhs_uk_conditions_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book
  https___www_nhs_uk_conditions_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens
  https___www_nhs_uk_conditions_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results
  https___www_nhs_uk_conditions_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_start_mode_change --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_pharmacy_type
  https___www_nhs_uk_tests_and_treatments --> https___www_nhs_uk_health_a_to_z
  https___www_nhs_uk_tests_and_treatments --> https___www_nhs_uk_tests_and_treatments_abdominal_aortic_aneurysm_screening
  https___www_nhs_uk_tests_and_treatments --> https___www_nhs_uk_tests_and_treatments_abortion
  https___www_nhs_uk_tests_and_treatments --> https___www_nhs_uk_tests_and_treatments_acl_anterior_cruciate_ligament_surgery
  https___111_nhs_uk_triage_check_its_not_an_emergency_journeyType_EmergencyPrescription --> https___111_nhs_uk_
  https___111_nhs_uk_triage_check_its_not_an_emergency_journeyType_EmergencyPrescription --> https___111_nhs_uk_Help_Terms
  https___111_nhs_uk_triage_check_its_not_an_emergency_journeyType_EmergencyPrescription --> https___111_nhs_uk_Help_Cookies
  https___111_nhs_uk_triage_check_its_not_an_emergency_journeyType_EmergencyPrescription --> https___111_nhs_uk_Help_Privacy
  https___111_nhs_uk_triage_check_its_not_an_emergency_journeyType_EmergencyPrescription --> https___111_nhs_uk_Help_Accessibility
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening --> https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support
  https___111_nhs_uk_Help_OtherWays_journeyType_EmergencyPrescription --> https___111_nhs_uk_
  https___111_nhs_uk_Help_OtherWays_journeyType_EmergencyPrescription --> https___111_nhs_uk_Help_Cookies
  https___111_nhs_uk_Help_OtherWays_journeyType_EmergencyPrescription --> https___111_nhs_uk_Help_Privacy
  https___111_nhs_uk_Help_OtherWays_journeyType_EmergencyPrescription --> https___111_nhs_uk_Help_Terms
  https___111_nhs_uk_Help_OtherWays_journeyType_EmergencyPrescription --> https___111_nhs_uk_Help_Accessibility
  https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening
  https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done --> https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited
  https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done --> https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book
  https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens
  https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done --> https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results
  https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done --> https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support
  https___111_nhs_uk_Help_Terms --> https___111_nhs_uk_
  https___111_nhs_uk_Help_Terms --> https___111_nhs_uk_Help_Cookies
  https___111_nhs_uk_Help_Terms --> https___111_nhs_uk_Help_Privacy
  https___111_nhs_uk_Help_Terms --> https___111_nhs_uk_Help_Accessibility
  https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited --> https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book
  https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening
  https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited --> https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done
  https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens
  https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited --> https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results
  https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited --> https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support
  https___111_nhs_uk_Help_Cookies --> https___111_nhs_uk_
  https___111_nhs_uk_Help_Cookies --> https___111_nhs_uk_Help_Privacy
  https___111_nhs_uk_Help_Cookies --> https___111_nhs_uk_Help_Terms
  https___111_nhs_uk_Help_Cookies --> https___111_nhs_uk_Help_Accessibility
  https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening
  https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book --> https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done
  https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book --> https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited
  https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens
  https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book --> https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results
  https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book --> https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support
  https___111_nhs_uk_Help_Privacy --> https___111_nhs_uk_
  https___111_nhs_uk_Help_Privacy --> https___111_nhs_uk_Help_Cookies
  https___111_nhs_uk_Help_Privacy --> https___111_nhs_uk_Help_Terms
  https___111_nhs_uk_Help_Privacy --> https___111_nhs_uk_Help_Accessibility
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens --> https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens --> https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens --> https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens --> https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results
  https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens --> https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support
  https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening
  https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results --> https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done
  https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results --> https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited
  https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results --> https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book
  https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens
  https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results --> https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support
  https___111_nhs_uk_Help_Accessibility --> https___111_nhs_uk_
  https___111_nhs_uk_Help_Accessibility --> https___111_nhs_uk_Help_Cookies
  https___111_nhs_uk_Help_Accessibility --> https___111_nhs_uk_Help_Privacy
  https___111_nhs_uk_Help_Accessibility --> https___111_nhs_uk_Help_Terms
  https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_is_cervical_screening
  https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support --> https___www_nhs_uk_tests_and_treatments_cervical_screening_why_its_done
  https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support --> https___www_nhs_uk_tests_and_treatments_cervical_screening_when_youll_be_invited
  https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support --> https___www_nhs_uk_tests_and_treatments_cervical_screening_how_to_book
  https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support --> https___www_nhs_uk_tests_and_treatments_cervical_screening_what_happens
  https___www_nhs_uk_tests_and_treatments_cervical_screening_further_help_and_support --> https___www_nhs_uk_tests_and_treatments_cervical_screening_your_results
  https___111_nhs_uk_triage_check_your_symptoms --> https___111_nhs_uk_
  https___111_nhs_uk_triage_check_your_symptoms --> https___111_nhs_uk_Help_Terms
  https___111_nhs_uk_triage_check_your_symptoms --> https___111_nhs_uk_Help_Cookies
  https___111_nhs_uk_triage_check_your_symptoms --> https___111_nhs_uk_Help_Privacy
  https___111_nhs_uk_triage_check_your_symptoms --> https___111_nhs_uk_Help_Accessibility
  https___www_nhs_uk_health_a_to_z --> https___www_nhs_uk_tests_and_treatments
  https___111_nhs_uk_guided_entry_dental_help --> https___111_nhs_uk_
  https___111_nhs_uk_guided_entry_dental_help --> https___111_nhs_uk_Help_Cookies
  https___111_nhs_uk_guided_entry_dental_help --> https___111_nhs_uk_Help_Privacy
  https___111_nhs_uk_guided_entry_dental_help --> https___111_nhs_uk_Help_Terms
  https___111_nhs_uk_guided_entry_dental_help --> https___111_nhs_uk_Help_Accessibility
  https___www_nhs_uk_tests_and_treatments_abdominal_aortic_aneurysm_screening --> https___www_nhs_uk_tests_and_treatments
  https___111_nhs_uk_guided_entry_mental_health_help --> https___111_nhs_uk_
  https___111_nhs_uk_guided_entry_mental_health_help --> https___111_nhs_uk_Help_Cookies
  https___111_nhs_uk_guided_entry_mental_health_help --> https___111_nhs_uk_Help_Privacy
  https___111_nhs_uk_guided_entry_mental_health_help --> https___111_nhs_uk_Help_Terms
  https___111_nhs_uk_guided_entry_mental_health_help --> https___111_nhs_uk_Help_Accessibility
  https___www_nhs_uk_tests_and_treatments_abortion --> https___www_nhs_uk_tests_and_treatments
  https___111_nhs_uk_guided_entry_sexual_health_help --> https___111_nhs_uk_
  https___111_nhs_uk_guided_entry_sexual_health_help --> https___111_nhs_uk_Help_Cookies
  https___111_nhs_uk_guided_entry_sexual_health_help --> https___111_nhs_uk_Help_Privacy
  https___111_nhs_uk_guided_entry_sexual_health_help --> https___111_nhs_uk_Help_Terms
  https___111_nhs_uk_guided_entry_sexual_health_help --> https___111_nhs_uk_Help_Accessibility
  https___www_nhs_uk_tests_and_treatments_acl_anterior_cruciate_ligament_surgery --> https___www_nhs_uk_tests_and_treatments

  classDef start fill:#53d8fb,stroke:#0f3460,color:#000
  classDef question fill:#e94560,stroke:#0f3460,color:#fff
  classDef confirmation fill:#4ecca3,stroke:#0f3460,color:#000
  classDef error fill:#ff6b6b,stroke:#0f3460,color:#fff
  class home,cervicalScreeningDetail,prescriptionStartRepeat start
