import XCTest

// Auto-generated by prototype-flow-map.
// This file is temporary — it is restored after screenshot capture.

final class FlowMapCapture: XCTestCase {

    override func setUpWithError() throws {
        // Continue on failure so all screens get a capture attempt.
        continueAfterFailure = true
    }

    // MARK: - Helpers

    /// Tap a tab bar button by label and/or index. Returns false if the tab was not found.
    /// Uses index-based tapping as the primary strategy (immune to label mismatches),
    /// with label-based fallbacks for robustness.
    @discardableResult
    func tapTab(_ label: String, index: Int, in app: XCUIApplication) -> Bool {
        // Wait for the splash screen to clear by waiting for the tab bar to settle.
        // Use a known home-screen element as the "ready" signal instead of just the tab bar,
        // since the tab bar element may exist in the hierarchy before the splash dismisses.
        Thread.sleep(forTimeInterval: 2.5) // cover the 2s splash + buffer
        let pred = NSPredicate(format: "label CONTAINS[c] %@", label)
        // 1. Index-based tap — reliable regardless of label text or badge counts
        if index >= 0 {
            let tabBar = app.tabBars.firstMatch
            if tabBar.exists {
                let btn = tabBar.buttons.element(boundBy: index)
                if btn.exists { btn.tap(); Thread.sleep(forTimeInterval: 0.5); return true }
            }
        }
        // 2. Exact label match within tab bar
        let exact = app.tabBars.buttons[label]
        if exact.exists { exact.tap(); Thread.sleep(forTimeInterval: 0.5); return true }
        // 3. Contains match within tab bar
        let fuzzy = app.tabBars.buttons.matching(pred).firstMatch
        if fuzzy.exists { fuzzy.tap(); Thread.sleep(forTimeInterval: 0.5); return true }
        // 4. Search all buttons (SwiftUI may not expose tab items under tabBars)
        let anyBtn = app.buttons.matching(pred).firstMatch
        if anyBtn.exists { anyBtn.tap(); Thread.sleep(forTimeInterval: 0.5); return true }
        return false
    }

    /// Find any tappable element matching one of the candidate labels and tap it.
    /// Prioritises interactive elements (buttons, cells) over static text to avoid
    /// accidentally tapping section headers or navigation titles.
    @discardableResult
    func tapElement(matching candidates: [String], in app: XCUIApplication) -> Bool {
        for (index, candidate) in candidates.enumerated() {
            let isLast = index == candidates.count - 1
            // 1. Button — exact label match (most common for navigation links)
            let btn = app.buttons[candidate]
            if btn.waitForExistence(timeout: 3) {
                btn.tap()
                Thread.sleep(forTimeInterval: 0.5)
                return true
            }
            // 2. Button — CONTAINS match (for buttons whose label includes subtitle text)
            let containsPred = NSPredicate(format: "label CONTAINS[c] %@", candidate)
            let fuzzyBtn = app.buttons.matching(containsPred).firstMatch
            if fuzzyBtn.waitForExistence(timeout: 0.5) {
                fuzzyBtn.tap()
                Thread.sleep(forTimeInterval: 0.5)
                return true
            }
            // 3. List / table cell
            let cell = app.cells[candidate]
            if cell.waitForExistence(timeout: 0.5) {
                cell.tap()
                Thread.sleep(forTimeInterval: 0.5)
                return true
            }
            // 4. Accessibility identifier
            let identPred = NSPredicate(format: "identifier ==[c] %@", candidate)
            let identEl = app.descendants(matching: .any).matching(identPred).firstMatch
            if identEl.waitForExistence(timeout: 0.5) {
                identEl.tap()
                Thread.sleep(forTimeInterval: 0.5)
                return true
            }
            // 5. Scroll and retry — only for the last candidate to avoid wasting time
            if isLast {
                var swiped = 0
                for _ in 0..<2 {
                    app.swipeUp()
                    swiped += 1
                    if btn.waitForExistence(timeout: 0.5) {
                        btn.tap()
                        Thread.sleep(forTimeInterval: 0.5)
                        return true
                    }
                    if cell.waitForExistence(timeout: 0.5) {
                        cell.tap()
                        Thread.sleep(forTimeInterval: 0.5)
                        return true
                    }
                }
                // Restore scroll position so subsequent taps/screenshots aren't affected
                for _ in 0..<swiped { app.swipeDown() }
            }
        }
        // No candidate found — leave the screen as-is and continue.
        return false
    }

    /// Write the current screen as a PNG to the given directory.
    func writeScreenshot(name: String, to dir: String) {
        let dirURL = URL(fileURLWithPath: dir)
        try? FileManager.default.createDirectory(at: dirURL, withIntermediateDirectories: true)
        let fileURL = dirURL.appendingPathComponent("\(name).png")
        try? XCUIScreen.main.screenshot().pngRepresentation.write(to: fileURL)
    }

    // MARK: - Screen captures

    func testCapture_HomeView() {
        print("📸 [flow-map] Capturing: HomeView")
        let app = XCUIApplication()
        app.launch()

        Thread.sleep(forTimeInterval: 5.0)
        writeScreenshot(name: "HomeView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: HomeView")
    }

    func testCapture_TrustedPersonDetailView() {
        print("📸 [flow-map] Capturing: TrustedPersonDetailView")
        let app = XCUIApplication()
        app.launch()

        Thread.sleep(forTimeInterval: 5.0)
        writeScreenshot(name: "TrustedPersonDetailView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: TrustedPersonDetailView")
    }

    func testCapture_ProfileSwitcherPersonView() {
        print("📸 [flow-map] Capturing: ProfileSwitcherPersonView")
        let app = XCUIApplication()
        app.launch()

        Thread.sleep(forTimeInterval: 5.0)
        writeScreenshot(name: "ProfileSwitcherPersonView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: ProfileSwitcherPersonView")
    }

    func testCapture_PrescriptionOrderStep1View() {
        print("📸 [flow-map] Capturing: PrescriptionOrderStep1View")
        let app = XCUIApplication()
        app.launch()

        Thread.sleep(forTimeInterval: 5.0)
        writeScreenshot(name: "PrescriptionOrderStep1View", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: PrescriptionOrderStep1View")
    }

    func testCapture_PrescriptionsView() {
        print("📸 [flow-map] Capturing: PrescriptionsView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Prescriptions"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Prescriptions\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "PrescriptionsView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: PrescriptionsView")
    }

    func testCapture_AppointmentsView() {
        print("📸 [flow-map] Capturing: AppointmentsView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Appointments"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Appointments\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "AppointmentsView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: AppointmentsView")
    }

    func testCapture_TestResultsView() {
        print("📸 [flow-map] Capturing: TestResultsView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Test results"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Test results\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "TestResultsView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: TestResultsView")
    }

    func testCapture_VaccinationsView() {
        print("📸 [flow-map] Capturing: VaccinationsView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Vaccinations"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Vaccinations\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "VaccinationsView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: VaccinationsView")
    }

    func testCapture_HealthConditionsView() {
        print("📸 [flow-map] Capturing: HealthConditionsView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Health conditions"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Health conditions\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "HealthConditionsView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: HealthConditionsView")
    }

    func testCapture_DocumentsView() {
        print("📸 [flow-map] Capturing: DocumentsView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Documents"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Documents\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "DocumentsView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: DocumentsView")
    }

    func testCapture_ProfileView() {
        print("📸 [flow-map] Capturing: ProfileView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["profile", "Profile"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"profile\", \"Profile\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "ProfileView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: ProfileView")
    }

    func testCapture_MessagesView() {
        print("📸 [flow-map] Capturing: MessagesView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["messages", "Messages"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"messages\", \"Messages\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "MessagesView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: MessagesView")
    }

    func testCapture_RemoveTrustedPersonView() {
        print("📸 [flow-map] Capturing: RemoveTrustedPersonView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Remove \\(profile.firstName)", "Remove Trusted Person"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Remove \\(profile.firstName)\", \"Remove Trusted Person\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "RemoveTrustedPersonView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: RemoveTrustedPersonView")
    }

    func testCapture_ProfileSwitchConfirmationView() {
        print("📸 [flow-map] Capturing: ProfileSwitchConfirmationView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Switch to \\(profile.firstName)'s profile", "Profile Switch Confirmation"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Switch to \\(profile.firstName)'s profile\", \"Profile Switch Confirmation\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "ProfileSwitchConfirmationView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: ProfileSwitchConfirmationView")
    }

    func testCapture_PrescriptionOrderStep2View() {
        print("📸 [flow-map] Capturing: PrescriptionOrderStep2View")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Start now", "Prescription Order Step2"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Start now\", \"Prescription Order Step2\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "PrescriptionOrderStep2View", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: PrescriptionOrderStep2View")
    }

    func testCapture_CheckPrescriptionsProgressView() {
        print("📸 [flow-map] Capturing: CheckPrescriptionsProgressView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Prescriptions"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Prescriptions\"]"); return }
        guard tapElement(matching: ["Check the progress of prescriptions", "Check Prescriptions Progress"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Check the progress of prescriptions\", \"Check Prescriptions Progress\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "CheckPrescriptionsProgressView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: CheckPrescriptionsProgressView")
    }

    func testCapture_DetailView() {
        print("📸 [flow-map] Capturing: DetailView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Prescriptions"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Prescriptions\"]"); return }
        guard tapElement(matching: ["Hospital and other medicines", "Detail"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Hospital and other medicines\", \"Detail\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "DetailView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: DetailView")
    }

    func testCapture_BookAppointmentView() {
        print("📸 [flow-map] Capturing: BookAppointmentView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Appointments"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Appointments\"]"); return }
        guard tapElement(matching: ["Book an appointment"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Book an appointment\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "BookAppointmentView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: BookAppointmentView")
    }

    func testCapture_GPAppointmentsView() {
        print("📸 [flow-map] Capturing: GPAppointmentsView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Appointments"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Appointments\"]"); return }
        guard tapElement(matching: ["Manage GP appointments", "GP appointments"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Manage GP appointments\", \"GP appointments\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "GPAppointmentsView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: GPAppointmentsView")
    }

    func testCapture_HealthChoicesView() {
        print("📸 [flow-map] Capturing: HealthChoicesView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["profile", "Profile"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"profile\", \"Profile\"]"); return }
        guard tapElement(matching: ["Health choices"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Health choices\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "HealthChoicesView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: HealthChoicesView")
    }

    func testCapture_CarePlansView() {
        print("📸 [flow-map] Capturing: CarePlansView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["profile", "Profile"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"profile\", \"Profile\"]"); return }
        guard tapElement(matching: ["Care plans"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Care plans\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "CarePlansView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: CarePlansView")
    }

    func testCapture_FaceIDView() {
        print("📸 [flow-map] Capturing: FaceIDView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["profile", "Profile"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"profile\", \"Profile\"]"); return }
        guard tapElement(matching: ["Face ID"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Face ID\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "FaceIDView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: FaceIDView")
    }

    func testCapture_CookiesView() {
        print("📸 [flow-map] Capturing: CookiesView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["profile", "Profile"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"profile\", \"Profile\"]"); return }
        guard tapElement(matching: ["Cookies", "Manage cookies"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Cookies\", \"Manage cookies\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "CookiesView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: CookiesView")
    }

    func testCapture_ComponentsView() {
        print("📸 [flow-map] Capturing: ComponentsView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["profile", "Profile"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"profile\", \"Profile\"]"); return }
        guard tapElement(matching: ["Components"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Components\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "ComponentsView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: ComponentsView")
    }

    func testCapture_RemovedMessagesView() {
        print("📸 [flow-map] Capturing: RemovedMessagesView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["messages", "Messages"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"messages\", \"Messages\"]"); return }
        guard tapElement(matching: ["Removed messages"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Removed messages\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "RemovedMessagesView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: RemovedMessagesView")
    }

    func testCapture_RemoveTrustedPersonReasonView() {
        print("📸 [flow-map] Capturing: RemoveTrustedPersonReasonView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Remove \\(profile.firstName)", "Remove Trusted Person"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Remove \\(profile.firstName)\", \"Remove Trusted Person\"]"); return }
        guard tapElement(matching: ["Start now", "Remove Trusted Person Reason"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Start now\", \"Remove Trusted Person Reason\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "RemoveTrustedPersonReasonView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: RemoveTrustedPersonReasonView")
    }

    func testCapture_PrescriptionOrderStep3View() {
        print("📸 [flow-map] Capturing: PrescriptionOrderStep3View")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Start now", "Prescription Order Step2"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Start now\", \"Prescription Order Step2\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step3"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step3\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "PrescriptionOrderStep3View", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: PrescriptionOrderStep3View")
    }

    func testCapture_RemoveTrustedPersonCheckAnswersView() {
        print("📸 [flow-map] Capturing: RemoveTrustedPersonCheckAnswersView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Remove \\(profile.firstName)", "Remove Trusted Person"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Remove \\(profile.firstName)\", \"Remove Trusted Person\"]"); return }
        guard tapElement(matching: ["Start now", "Remove Trusted Person Reason"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Start now\", \"Remove Trusted Person Reason\"]"); return }
        guard tapElement(matching: ["Continue", "Remove Trusted Person Check Answers"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Remove Trusted Person Check Answers\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "RemoveTrustedPersonCheckAnswersView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: RemoveTrustedPersonCheckAnswersView")
    }

    func testCapture_PrescriptionOrderStep4View() {
        print("📸 [flow-map] Capturing: PrescriptionOrderStep4View")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Start now", "Prescription Order Step2"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Start now\", \"Prescription Order Step2\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step3"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step3\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step4"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step4\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "PrescriptionOrderStep4View", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: PrescriptionOrderStep4View")
    }

    func testCapture_RemoveTrustedPersonConfirmationView() {
        print("📸 [flow-map] Capturing: RemoveTrustedPersonConfirmationView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Remove \\(profile.firstName)", "Remove Trusted Person"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Remove \\(profile.firstName)\", \"Remove Trusted Person\"]"); return }
        guard tapElement(matching: ["Start now", "Remove Trusted Person Reason"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Start now\", \"Remove Trusted Person Reason\"]"); return }
        guard tapElement(matching: ["Continue", "Remove Trusted Person Check Answers"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Remove Trusted Person Check Answers\"]"); return }
        guard tapElement(matching: ["Confirm and remove", "Remove Trusted Person Confirmation"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Confirm and remove\", \"Remove Trusted Person Confirmation\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "RemoveTrustedPersonConfirmationView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: RemoveTrustedPersonConfirmationView")
    }

    func testCapture_PrescriptionOrderStep5View() {
        print("📸 [flow-map] Capturing: PrescriptionOrderStep5View")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Start now", "Prescription Order Step2"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Start now\", \"Prescription Order Step2\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step3"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step3\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step4"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step4\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step5"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step5\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "PrescriptionOrderStep5View", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: PrescriptionOrderStep5View")
    }

    func testCapture_PrescriptionOrderStep6View() {
        print("📸 [flow-map] Capturing: PrescriptionOrderStep6View")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Start now", "Prescription Order Step2"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Start now\", \"Prescription Order Step2\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step3"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step3\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step4"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step4\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step5"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step5\"]"); return }
        guard tapElement(matching: ["Confirm request", "Prescription Order Step6"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Confirm request\", \"Prescription Order Step6\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "PrescriptionOrderStep6View", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured: PrescriptionOrderStep6View")
    }

    func testCapture_modal_PrototypeSettingsView() {
        print("📸 [flow-map] Capturing modal: PrototypeSettingsView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["profile", "Profile"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"profile\", \"Profile\"]"); return }
        guard tapElement(matching: ["Prototype settings"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Prototype settings\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "PrototypeSettingsView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured modal: PrototypeSettingsView")
    }

    func testCapture_modal_BookAppointmentStartPage() {
        print("📸 [flow-map] Capturing modal: BookAppointmentStartPage")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Appointments"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Appointments\"]"); return }
        guard tapElement(matching: ["Manage GP appointments", "GP appointments"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Manage GP appointments\", \"GP appointments\"]"); return }
        guard tapElement(matching: ["Book GP appointment"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Book GP appointment\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "BookAppointmentStartPage", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured modal: BookAppointmentStartPage")
    }

    func testCapture_modal_PatchsStartPage() {
        print("📸 [flow-map] Capturing modal: PatchsStartPage")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Appointments"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Appointments\"]"); return }
        guard tapElement(matching: ["Book an appointment"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Book an appointment\"]"); return }
        guard tapElement(matching: ["Ask about a health problem"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Ask about a health problem\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "PatchsStartPage", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured modal: PatchsStartPage")
    }

    func testCapture_modal_ProfileSwitcherView() {
        print("📸 [flow-map] Capturing modal: ProfileSwitcherView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["profile", "Profile"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"profile\", \"Profile\"]"); return }
        guard tapElement(matching: ["Profile Switcher"], in: app) else { print("⚠️ [flow-map] tapElement failed (auto-label): [\"Profile Switcher\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "ProfileSwitcherView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured modal: ProfileSwitcherView")
    }

    func testCapture_modal_ChangePharmacySheet() {
        print("📸 [flow-map] Capturing modal: ChangePharmacySheet")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Start now", "Prescription Order Step2"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Start now\", \"Prescription Order Step2\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step3"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step3\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step4"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step4\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step5"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step5\"]"); return }
        guard tapElement(matching: ["Change Pharmacy Sheet"], in: app) else { print("⚠️ [flow-map] tapElement failed (auto-label): [\"Change Pharmacy Sheet\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "ChangePharmacySheet", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured modal: ChangePharmacySheet")
    }

    func testCapture_modal_EditMedicinesSheet() {
        print("📸 [flow-map] Capturing modal: EditMedicinesSheet")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Start now", "Prescription Order Step2"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Start now\", \"Prescription Order Step2\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step3"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step3\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step4"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step4\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step5"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step5\"]"); return }
        guard tapElement(matching: ["Edit Medicines Sheet"], in: app) else { print("⚠️ [flow-map] tapElement failed (auto-label): [\"Edit Medicines Sheet\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "EditMedicinesSheet", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured modal: EditMedicinesSheet")
    }

    func testCapture_modal_EditInformationSheet() {
        print("📸 [flow-map] Capturing modal: EditInformationSheet")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Start now", "Prescription Order Step2"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Start now\", \"Prescription Order Step2\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step3"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step3\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step4"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step4\"]"); return }
        guard tapElement(matching: ["Continue", "Prescription Order Step5"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Continue\", \"Prescription Order Step5\"]"); return }
        guard tapElement(matching: ["Edit Information Sheet"], in: app) else { print("⚠️ [flow-map] tapElement failed (auto-label): [\"Edit Information Sheet\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "EditInformationSheet", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured modal: EditInformationSheet")
    }

    func testCapture_modal_AppointmentDetailView() {
        print("📸 [flow-map] Capturing modal: AppointmentDetailView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["Appointments"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Appointments\"]"); return }
        guard tapElement(matching: ["Manage GP appointments", "GP appointments"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Manage GP appointments\", \"GP appointments\"]"); return }
        guard tapElement(matching: ["Appointment Detail"], in: app) else { print("⚠️ [flow-map] tapElement failed (auto-label): [\"Appointment Detail\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "AppointmentDetailView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured modal: AppointmentDetailView")
    }

    func testCapture_modalChild_AddCareProfileView() {
        print("📸 [flow-map] Capturing modal child: AddCareProfileView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["profile", "Profile"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"profile\", \"Profile\"]"); return }
        guard tapElement(matching: ["Profile Switcher"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Profile Switcher\"]"); return }
        guard tapElement(matching: ["Add someone you care for", "Add Care Profile"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Add someone you care for\", \"Add Care Profile\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "AddCareProfileView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured modal child: AddCareProfileView")
    }

    func testCapture_modalChild_AddTrustedPersonView() {
        print("📸 [flow-map] Capturing modal child: AddTrustedPersonView")
        let app = XCUIApplication()
        app.launch()
        guard tapElement(matching: ["profile", "Profile"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"profile\", \"Profile\"]"); return }
        guard tapElement(matching: ["Profile Switcher"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Profile Switcher\"]"); return }
        guard tapElement(matching: ["Add a trusted person", "Add Trusted Person"], in: app) else { print("⚠️ [flow-map] tapElement failed: [\"Add a trusted person\", \"Add Trusted Person\"]"); return }
        Thread.sleep(forTimeInterval: 2.0)
        writeScreenshot(name: "AddTrustedPersonView", to: "/tmp/flow-map-ios-1777318713044")
        print("✅ [flow-map] Captured modal child: AddTrustedPersonView")
    }
}
