flowchart TD
  VaccinationsView["Vaccinations"]
  TestResultsView["Test results"]
  PrototypeSettingsView["Prototype settings"]
  HomeView["Home"]
  HealthConditionsView["Health conditions"]
  DocumentsView["Documents"]
  TrustedPersonDetailView["Trusted Person Detail"]
  RemoveTrustedPersonView["Remove Trusted Person"]
  RemoveTrustedPersonReasonView["Remove Trusted Person Reason"]
  RemoveTrustedPersonCheckAnswersView["Remove Trusted Person Check Answers"]
  ProfileView["Profile"]
  ProfileSwitcherView["Profile Switcher"]
  ProfileSwitcherPersonView["Profile Switcher Person"]
  HealthChoicesView["Health choices"]
  CookiesView["Manage cookies"]
  CarePlansView["Care plans"]
  PrescriptionsView["Prescriptions"]
  CheckPrescriptionsProgressView["Check Prescriptions Progress"]
  PrescriptionOrderStep5View["Prescription Order Step5"]
  PrescriptionOrderStep4View["Prescription Order Step4"]
  PrescriptionOrderStep3View["Prescription Order Step3"]
  PrescriptionOrderStep2View["Prescription Order Step2"]
  PrescriptionOrderStep1View["Prescription Order Step1"]
  MessagesView["Messages"]
  UrgentMedicalHelpSection["Urgent Medical Help Section"]
  PatchsStartPage["Patchs Start"]
  PastGPAppointmentsView["Past appointments"]
  NoAppointmentsView["No Appointments"]
  GPAppointmentsView["GP appointments"]
  BookAppointmentView["Book an appointment"]
  BookAppointmentStartPage["Book Appointment Start"]
  AppointmentsView["Appointments"]
  DetailView["Detail"]
  RemoveTrustedPersonConfirmationView["Remove Trusted Person Confirmation"]
  FaceIDView["Face ID"]
  ComponentsView["Components"]
  AddCareProfileView["Add Care Profile"]
  AddTrustedPersonView["Add Trusted Person"]
  ProfileSwitchConfirmationView["Profile Switch Confirmation"]
  PrescriptionOrderStep6View["Prescription Order Step6"]
  ChangePharmacySheet["Change Pharmacy Sheet"]
  EditMedicinesSheet["Edit Medicines Sheet"]
  EditInformationSheet["Edit Information Sheet"]
  RemovedMessagesView["Removed messages"]
  AppointmentDetailView["GP appointment"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_clear_data["Clear data"]
  https___www_nhs_uk_nhs_app_help["Help with using the NHS App - NHS"]
  https___111_nhs_uk_["Get help for your symptoms - NHS 111"]
  https___www_nhs_uk_health_a_to_z["Health A to Z - NHS"]
  https___www_nhs_uk_nhs_services_services_near_you["Find services near you - NHS"]
  https___feedback_digital_nhs_uk_jfe_form_SV_cZPlxXgJ3RnKwya["Qualtrics Survey | Qualtrics Experience Management"]
  https___www_nhs_uk_nhs_app_about_nhs_app_legal_and_cookies["NHS App legal and cookies - NHS"]
  https___www_nhs_uk_nhs_app_about_nhs_app_legal_and_cookies_nhs_app_cookies_policy["NHS App cookies policy - NHS"]
  https___www_nhs_uk_nhs_app_help_prescriptions_in_the_nhs_app["Prescriptions – NHS App - NHS"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_check_the_pharmacy["Check your chosen pharmacy - NHS App prototype"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_and_past_medicines["Medicines record - NHS App prototype"]
  https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App["Emergency prescriptions - NHS 111"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_start["Choose a pharmacy - NHS App prototype"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_requested_medicines["Check if your GP has approved a request - NHS App prototype"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_approved_prescriptions["Check prescriptions with the pharmacy - NHS App prototype"]
  https___nhsapp_native_test_6c35b83d719e_herokuapp_com_pages_integrations_patchs_index["Patchs - Online Consultation"]
  https___www_nhs_uk_nhs_app_about_nhs_app_legal_and_cookies_nhs_app_privacy_policy_online_consultation_services["NHS App privacy policy: online consultation services - Version 3 - 30 March 2023"]
  https___nhsapp_native_test_6c35b83d719e_herokuapp_com_pages_services_gp_appointment_type["Select an appointment type - NHS App prototype"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_start_mode_change["Change your pharmacy - NHS App prototype"]
  https___www_nhs_uk_nhs_app["NHS App - NHS"]
  https___111_nhs_uk_triage_check_your_symptoms["Check your symptoms - NHS 111"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_select_medicines["Choose the medicines you need - NHS App prototype"]
  https___www_nhs_uk_nhs_app_about_what_is_new["What's new in the NHS App – NHS App help - NHS"]
  https___111_nhs_uk_guided_entry_dental_help["Get dental help - NHS 111"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_one_off_medicines["One-off medicines - NHS App prototype"]
  https___www_nhs_uk_nhs_app_help_logging_in["Logging in to the NHS App – NHS App help - NHS"]
  https___111_nhs_uk_guided_entry_mental_health_help["Get mental health help - NHS 111"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_repeat_medicines["Current repeat medicines - NHS App prototype"]
  https___www_nhs_uk_nhs_app_help_prescriptions["Prescriptions – NHS App - NHS"]
  https___111_nhs_uk_guided_entry_sexual_health_help["Get sexual health help - NHS 111"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_past_repeat_medicines["Past repeat medicines - NHS App prototype"]
  https___www_nhs_uk_nhs_app_help_appointments["Appointments – NHS App help - NHS"]
  https___111_nhs_uk_guided_entry_medicines_help["Get a prescription or medicines information - NHS 111"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_pharmacy_type["Choose a type of pharmacy - NHS App prototype"]
  https___www_nhs_uk_nhs_app_help_test_results["Viewing test results – NHS App - NHS"]
  https___111_nhs_uk_Help_OtherWays["Other ways to contact 111 - NHS 111"]
  https___www_nhs_uk_nhs_app_help_vaccinations["Vaccinations – NHS App help - NHS"]
  https___111_nhs_uk_Help_Cookies["Cookies on 111.nhs.uk - NHS 111"]
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_prescription["Your prescription - NHS App prototype"]
  https___www_nhs_uk_nhs_app_help_health_conditions_allergies["Health conditions and allergies – NHS App - NHS"]

  VaccinationsView --> DetailView
  TestResultsView --> DetailView
  PrototypeSettingsView --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_clear_data
  HomeView --> PrescriptionsView
  HomeView --> AppointmentsView
  HomeView --> TestResultsView
  HomeView --> VaccinationsView
  HomeView --> HealthConditionsView
  HomeView --> DocumentsView
  HomeView --> ProfileView
  HomeView --> MessagesView
  HomeView --> https___www_nhs_uk_nhs_app_help
  HomeView --> https___111_nhs_uk_
  HomeView --> https___www_nhs_uk_health_a_to_z
  HomeView --> https___www_nhs_uk_nhs_services_services_near_you
  HomeView --> https___feedback_digital_nhs_uk_jfe_form_SV_cZPlxXgJ3RnKwya
  HealthConditionsView --> DetailView
  DocumentsView --> DetailView
  TrustedPersonDetailView --> RemoveTrustedPersonView
  RemoveTrustedPersonView --> RemoveTrustedPersonReasonView
  RemoveTrustedPersonReasonView --> RemoveTrustedPersonCheckAnswersView
  RemoveTrustedPersonCheckAnswersView --> RemoveTrustedPersonConfirmationView
  ProfileView --> DetailView
  ProfileView --> HealthChoicesView
  ProfileView --> CarePlansView
  ProfileView --> FaceIDView
  ProfileView --> CookiesView
  ProfileView --> ComponentsView
  ProfileView --> PrototypeSettingsView
  ProfileView --> ProfileSwitcherView
  ProfileView --> https___www_nhs_uk_nhs_app_help
  ProfileView --> https___www_nhs_uk_nhs_app_about_nhs_app_legal_and_cookies
  ProfileSwitcherView --> ProfileSwitcherPersonView
  ProfileSwitcherView --> TrustedPersonDetailView
  ProfileSwitcherView --> AddCareProfileView
  ProfileSwitcherView --> AddTrustedPersonView
  ProfileSwitcherPersonView --> ProfileSwitchConfirmationView
  HealthChoicesView --> DetailView
  CookiesView --> https___www_nhs_uk_nhs_app_about_nhs_app_legal_and_cookies_nhs_app_cookies_policy
  CarePlansView --> DetailView
  PrescriptionsView --> CheckPrescriptionsProgressView
  PrescriptionsView --> DetailView
  PrescriptionsView --> https___www_nhs_uk_nhs_app_help_prescriptions_in_the_nhs_app
  PrescriptionsView --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_check_the_pharmacy
  PrescriptionsView --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_and_past_medicines
  PrescriptionsView --> https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App
  PrescriptionsView --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_start
  CheckPrescriptionsProgressView --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_requested_medicines
  CheckPrescriptionsProgressView --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_approved_prescriptions
  PrescriptionOrderStep5View --> PrescriptionOrderStep6View
  PrescriptionOrderStep5View --> ChangePharmacySheet
  PrescriptionOrderStep5View --> EditMedicinesSheet
  PrescriptionOrderStep5View --> EditInformationSheet
  PrescriptionOrderStep4View --> PrescriptionOrderStep5View
  PrescriptionOrderStep3View --> PrescriptionOrderStep4View
  PrescriptionOrderStep2View --> PrescriptionOrderStep3View
  PrescriptionOrderStep2View --> ChangePharmacySheet
  PrescriptionOrderStep1View --> PrescriptionOrderStep2View
  MessagesView --> RemovedMessagesView
  UrgentMedicalHelpSection --> https___111_nhs_uk_
  PatchsStartPage --> https___nhsapp_native_test_6c35b83d719e_herokuapp_com_pages_integrations_patchs_index
  PatchsStartPage --> https___www_nhs_uk_nhs_app_about_nhs_app_legal_and_cookies_nhs_app_privacy_policy_online_consultation_services
  PastGPAppointmentsView --> AppointmentDetailView
  NoAppointmentsView --> AppointmentDetailView
  NoAppointmentsView --> BookAppointmentStartPage
  NoAppointmentsView --> PatchsStartPage
  GPAppointmentsView --> AppointmentDetailView
  GPAppointmentsView --> BookAppointmentStartPage
  BookAppointmentView --> AppointmentDetailView
  BookAppointmentView --> BookAppointmentStartPage
  BookAppointmentView --> PatchsStartPage
  BookAppointmentStartPage --> https___nhsapp_native_test_6c35b83d719e_herokuapp_com_pages_services_gp_appointment_type
  AppointmentsView --> BookAppointmentView
  AppointmentsView --> GPAppointmentsView
  AppointmentsView --> DetailView
  AppointmentsView --> AppointmentDetailView
  AppointmentsView --> BookAppointmentStartPage
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_check_the_pharmacy --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_start_mode_change
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_check_the_pharmacy --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_select_medicines
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_and_past_medicines --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_one_off_medicines
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_and_past_medicines --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_repeat_medicines
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_current_and_past_medicines --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_repeat_prescription_medicines_record_past_repeat_medicines
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_start --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_pharmacy_type
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_requested_medicines --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_approved_prescriptions
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_approved_prescriptions --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_your_prescription
  https___www_nhs_uk_nhs_app_help --> https___www_nhs_uk_nhs_app
  https___www_nhs_uk_nhs_app_help --> https___www_nhs_uk_nhs_app_about_what_is_new
  https___www_nhs_uk_nhs_app_help --> https___www_nhs_uk_nhs_app_help_logging_in
  https___www_nhs_uk_nhs_app_help --> https___www_nhs_uk_nhs_app_help_prescriptions
  https___www_nhs_uk_nhs_app_help --> https___www_nhs_uk_nhs_app_help_appointments
  https___www_nhs_uk_nhs_app_help --> https___www_nhs_uk_nhs_app_help_test_results
  https___www_nhs_uk_nhs_app_help --> https___www_nhs_uk_nhs_app_help_vaccinations
  https___www_nhs_uk_nhs_app_help --> https___www_nhs_uk_nhs_app_help_health_conditions_allergies
  https___www_nhs_uk_nhs_app_about_nhs_app_legal_and_cookies --> https___www_nhs_uk_nhs_app_about_nhs_app_legal_and_cookies_nhs_app_cookies_policy
  https___www_nhs_uk_nhs_app_about_nhs_app_legal_and_cookies_nhs_app_cookies_policy --> https___www_nhs_uk_nhs_app_about_nhs_app_legal_and_cookies
  https___www_nhs_uk_nhs_app_help_prescriptions_in_the_nhs_app --> https___www_nhs_uk_nhs_app_help
  https___111_nhs_uk_ --> https___111_nhs_uk_triage_check_your_symptoms
  https___111_nhs_uk_ --> https___111_nhs_uk_guided_entry_dental_help
  https___111_nhs_uk_ --> https___111_nhs_uk_guided_entry_mental_health_help
  https___111_nhs_uk_ --> https___111_nhs_uk_guided_entry_sexual_health_help
  https___111_nhs_uk_ --> https___111_nhs_uk_guided_entry_medicines_help
  https___111_nhs_uk_ --> https___111_nhs_uk_Help_OtherWays
  https___111_nhs_uk_ --> https___111_nhs_uk_Help_Cookies
  https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App --> https___111_nhs_uk_
  https___111_nhs_uk_emergency_prescription_utm_content_Emergency_Prescription_utm_source_NHS_App --> https___111_nhs_uk_Help_Cookies
  https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_start_mode_change --> https___nhsapp_prescriptions_native_85d8ccd5903e_herokuapp_com_pages_your_health_choose_pharmacy_pharmacy_type
  https___www_nhs_uk_nhs_app --> https___www_nhs_uk_nhs_app_help
  https___111_nhs_uk_triage_check_your_symptoms --> https___111_nhs_uk_
  https___111_nhs_uk_triage_check_your_symptoms --> https___111_nhs_uk_Help_OtherWays
  https___111_nhs_uk_triage_check_your_symptoms --> https___111_nhs_uk_Help_Cookies
  https___www_nhs_uk_nhs_app_about_what_is_new --> https___www_nhs_uk_nhs_app_help
  https___www_nhs_uk_nhs_app_about_what_is_new --> https___www_nhs_uk_nhs_app_about_nhs_app_legal_and_cookies
  https___111_nhs_uk_guided_entry_dental_help --> https___111_nhs_uk_
  https___111_nhs_uk_guided_entry_dental_help --> https___111_nhs_uk_Help_Cookies
  https___www_nhs_uk_nhs_app_help_logging_in --> https___www_nhs_uk_nhs_app_help
  https___www_nhs_uk_nhs_app_help_logging_in --> https___www_nhs_uk_nhs_app_about_what_is_new
  https___111_nhs_uk_guided_entry_mental_health_help --> https___111_nhs_uk_
  https___111_nhs_uk_guided_entry_mental_health_help --> https___111_nhs_uk_Help_Cookies
  https___www_nhs_uk_nhs_app_help_prescriptions --> https___www_nhs_uk_nhs_app_help
  https___111_nhs_uk_guided_entry_sexual_health_help --> https___111_nhs_uk_
  https___111_nhs_uk_guided_entry_sexual_health_help --> https___111_nhs_uk_Help_Cookies
  https___www_nhs_uk_nhs_app_help_appointments --> https___www_nhs_uk_nhs_app_help
  https___111_nhs_uk_guided_entry_medicines_help --> https___111_nhs_uk_
  https___111_nhs_uk_guided_entry_medicines_help --> https___111_nhs_uk_Help_Cookies
  https___www_nhs_uk_nhs_app_help_test_results --> https___www_nhs_uk_nhs_app_help
  https___www_nhs_uk_nhs_app_help_test_results --> https___www_nhs_uk_nhs_app_about_what_is_new
  https___111_nhs_uk_Help_OtherWays --> https___111_nhs_uk_
  https___111_nhs_uk_Help_OtherWays --> https___111_nhs_uk_Help_Cookies
  https___www_nhs_uk_nhs_app_help_vaccinations --> https___www_nhs_uk_nhs_app_help
  https___111_nhs_uk_Help_Cookies --> https___111_nhs_uk_
  https___www_nhs_uk_nhs_app_help_health_conditions_allergies --> https___www_nhs_uk_nhs_app_help

  classDef start fill:#53d8fb,stroke:#0f3460,color:#000
  classDef question fill:#e94560,stroke:#0f3460,color:#fff
  classDef confirmation fill:#4ecca3,stroke:#0f3460,color:#000
  classDef error fill:#ff6b6b,stroke:#0f3460,color:#fff
  class HomeView,ProfileView,PrescriptionsView,PrescriptionOrderStep1View,UrgentMedicalHelpSection,PastGPAppointmentsView,NoAppointmentsView,AppointmentsView,https___www_nhs_uk_nhs_app_help,https___111_nhs_uk_ start
