package com.nhs.online.nhsonline.proto

// Auto-generated by prototype-flow-map.
// This file is temporary — the tool writes it at run time and deletes it
// afterwards. Do not edit or commit.

import android.content.Context
import android.graphics.Bitmap
import android.util.Log
import androidx.compose.ui.graphics.asAndroidBitmap
import androidx.compose.ui.test.captureToImage
import androidx.compose.ui.test.junit4.createAndroidComposeRule
import androidx.compose.ui.test.onRoot
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.nhs.online.nhsonline.proto.navigation.TestHooks
import org.junit.Before
import org.junit.BeforeClass
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File
import java.io.FileOutputStream

@RunWith(AndroidJUnit4::class)
class FlowMapCapture {

    companion object {
        @JvmStatic
        @BeforeClass
        fun skipOnboarding() {
            val ctx = InstrumentationRegistry.getInstrumentation().targetContext
            ctx.getSharedPreferences("onboarding", Context.MODE_PRIVATE)
                .edit()
                .putBoolean("completed", true)
                .commit()
        }
    }

    @get:Rule
    val composeTestRule = createAndroidComposeRule<com.nhs.online.nhsonline.proto.MainActivity>()

    @Before
    fun waitForNavController() {
        composeTestRule.waitUntil(timeoutMillis = 10_000) {
            TestHooks.navController != null
        }
    }

    private fun writeScreenshot(name: String) {
        val bitmap = composeTestRule.onRoot().captureToImage().asAndroidBitmap()
        val ctx = InstrumentationRegistry.getInstrumentation().targetContext
        val dir = File(ctx.externalCacheDir, "flow-map").apply { mkdirs() }
        val file = File(dir, "$name.png")
        FileOutputStream(file).use { bitmap.compress(Bitmap.CompressFormat.PNG, 100, it) }
        Log.d("FlowMapCapture", "Wrote ${file.absolutePath} size=${file.length()}")
    }

    private fun navigateAndCapture(route: String, name: String) {
        try {
            composeTestRule.runOnUiThread { TestHooks.navController!!.navigate(route) }
        } catch (t: Throwable) {
            Log.w("FlowMapCapture", "navigate(\"$route\") threw: ${t.message}")
        }
        composeTestRule.waitForIdle()
        Thread.sleep(500)
        writeScreenshot(name)
    }

    // --- Per-screen captures ---

    @Test
    fun testCapture_home() {
        navigateAndCapture("home", "home")
    }

    @Test
    fun testCapture_messages() {
        navigateAndCapture("messages", "messages")
    }

    @Test
    fun testCapture_profile() {
        navigateAndCapture("profile", "profile")
    }

    @Test
    fun testCapture_biometricLogin() {
        navigateAndCapture("biometricLogin", "biometricLogin")
    }

    @Test
    fun testCapture_familyCarer() {
        navigateAndCapture("familyCarer", "familyCarer")
    }

    @Test
    fun testCapture_familyCarer_addCaredFor() {
        navigateAndCapture("familyCarer/addCaredFor", "familyCarer_addCaredFor")
    }

    @Test
    fun testCapture_familyCarer_addTrusted() {
        navigateAndCapture("familyCarer/addTrusted", "familyCarer_addTrusted")
    }

    @Test
    fun testCapture_familyCarer_caredFor() {
        navigateAndCapture("familyCarer/caredFor/1", "familyCarer_caredFor")
    }

    @Test
    fun testCapture_familyCarer_caredFor_confirm() {
        navigateAndCapture("familyCarer/caredFor/1/confirm", "familyCarer_caredFor_confirm")
    }

    @Test
    fun testCapture_familyCarer_trusted() {
        navigateAndCapture("familyCarer/trusted/trusted-1", "familyCarer_trusted")
    }

    @Test
    fun testCapture_familyCarer_trusted_remove() {
        navigateAndCapture("familyCarer/trusted/trusted-1/remove", "familyCarer_trusted_remove")
    }

    @Test
    fun testCapture_familyCarer_trusted_reason() {
        navigateAndCapture("familyCarer/trusted/trusted-1/reason", "familyCarer_trusted_reason")
    }

    @Test
    fun testCapture_familyCarer_trusted_confirm() {
        navigateAndCapture("familyCarer/trusted/trusted-1/confirm", "familyCarer_trusted_confirm")
    }

    @Test
    fun testCapture_familyCarer_trusted_success() {
        navigateAndCapture("familyCarer/trusted/trusted-1/success", "familyCarer_trusted_success")
    }

    @Test
    fun testCapture_prescriptions2() {
        navigateAndCapture("prescriptions2", "prescriptions2")
    }

    @Test
    fun testCapture_appointments() {
        navigateAndCapture("appointments", "appointments")
    }

    @Test
    fun testCapture_referrals() {
        navigateAndCapture("referrals", "referrals")
    }

    @Test
    fun testCapture_cervicalScreeningDetail() {
        navigateAndCapture("cervicalScreeningDetail", "cervicalScreeningDetail")
    }

    @Test
    fun testCapture_bookAppointmentMenu() {
        navigateAndCapture("bookAppointmentMenu", "bookAppointmentMenu")
    }

    @Test
    fun testCapture_askHealthProblemStart() {
        navigateAndCapture("askHealthProblemStart", "askHealthProblemStart")
    }

    @Test
    fun testCapture_bookAppointmentStart() {
        navigateAndCapture("bookAppointmentStart", "bookAppointmentStart")
    }

    @Test
    fun testCapture_noAppointmentsAvailable() {
        navigateAndCapture("noAppointmentsAvailable", "noAppointmentsAvailable")
    }

    @Test
    fun testCapture_prescriptionStartRepeat() {
        navigateAndCapture("prescriptionStartRepeat", "prescriptionStartRepeat")
    }

    @Test
    fun testCapture_checkPrescriptions() {
        navigateAndCapture("checkPrescriptions", "checkPrescriptions")
    }

    @Test
    fun testCapture_prescriptionAddPharmacy() {
        navigateAndCapture("prescriptionAddPharmacy", "prescriptionAddPharmacy")
    }

    @Test
    fun testCapture_prescriptionPharmacyDetail() {
        navigateAndCapture("prescriptionPharmacyDetail/1?editMode=false", "prescriptionPharmacyDetail")
    }

    @Test
    fun testCapture_prescriptionMedicineDetail() {
        navigateAndCapture("prescriptionMedicineDetail/1", "prescriptionMedicineDetail")
    }

    @Test
    fun testCapture_prescriptionConfirmationRepeat() {
        navigateAndCapture("prescriptionConfirmationRepeat/1/1/1/1", "prescriptionConfirmationRepeat")
    }

    @Test
    fun testCapture_prescriptionAdditionalDetail() {
        navigateAndCapture("prescriptionAdditionalDetail/1", "prescriptionAdditionalDetail")
    }

    @Test
    fun testCapture_prescriptionFormRepeat() {
        navigateAndCapture("prescriptionFormRepeat", "prescriptionFormRepeat")
    }

    @Test
    fun testCapture_message_detail() {
        navigateAndCapture("message_detail/1", "message_detail")
    }

    @Test
    fun testCapture_archived_messages() {
        navigateAndCapture("archived_messages", "archived_messages")
    }

    @Test
    fun testCapture_prescriptionDetail() {
        navigateAndCapture("prescriptionDetail", "prescriptionDetail")
    }
}
