package com.prototype.nhsappav1

// Auto-generated by prototype-flow-map.
// This file is temporary — it is restored after screenshot capture.

import android.app.Activity
import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.createEmptyComposeRule
import androidx.test.core.app.ActivityScenario
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import androidx.test.uiautomator.UiDevice
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File

@RunWith(AndroidJUnit4::class)
class FlowMapCapture {

    @get:Rule
    val composeTestRule = createEmptyComposeRule()

    private lateinit var device: UiDevice
    private var scenario: ActivityScenario<MainActivity>? = null
    private val screenshotsDir = "/sdcard/Download/flow-map-screenshots"

    @Before
    fun setUp() {
        device = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())
        // Create screenshots directory on device
        device.executeShellCommand("mkdir -p $screenshotsDir")
        // Bypass onboarding
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        context.getSharedPreferences("onboarding", android.content.Context.MODE_PRIVATE)
            .edit().putBoolean("completed", true).apply()
        // Clear prescription drafts
        context.getSharedPreferences("prescription_drafts", android.content.Context.MODE_PRIVATE)
            .edit().clear().apply()
    }

    // --- Helpers ---

    private fun launchApp() {
        scenario?.close()
        scenario = ActivityScenario.launch(MainActivity::class.java)
        // Wait for the app to settle
        composeTestRule.waitForIdle()
        Thread.sleep(3000)
    }

    /**
     * Tap a navigation item by label text.
     * Tries merged tree first (NavigationBarItem merges label text), then unmerged.
     */
    private fun tapTab(label: String): Boolean {
        try {
            val nodes = composeTestRule.onAllNodesWithText(label)
                .fetchSemanticsNodes()
            if (nodes.isNotEmpty()) {
                composeTestRule.onAllNodesWithText(label)[0]
                    .performClick()
                composeTestRule.waitForIdle()
                Thread.sleep(1000)
                return true
            }
        } catch (_: Throwable) {}

        try {
            val nodes = composeTestRule.onAllNodesWithText(label, substring = true)
                .fetchSemanticsNodes()
            if (nodes.isNotEmpty()) {
                composeTestRule.onAllNodesWithText(label, substring = true)[0]
                    .performClick()
                composeTestRule.waitForIdle()
                Thread.sleep(1000)
                return true
            }
        } catch (_: Throwable) {}

        return false
    }

    /**
     * Find a tappable element matching one of the candidate labels and tap it.
     * For each candidate tries: merged-tree exact, merged-tree substring,
     * unmerged-tree exact, unmerged-tree substring, content description.
     * Using the merged tree first means parent clickable containers (which merge
     * child Text nodes into their semantics) are found and clicked correctly.
     */
    private fun tapElement(candidates: List<String>): Boolean {
        for (candidate in candidates) {
            // 1. Merged tree exact text (click action lives on parent container)
            try {
                val nodes = composeTestRule.onAllNodesWithText(candidate)
                    .fetchSemanticsNodes()
                if (nodes.isNotEmpty()) {
                    composeTestRule.onAllNodesWithText(candidate)[0]
                        .performClick()
                    composeTestRule.waitForIdle()
                    Thread.sleep(1000)
                    return true
                }
            } catch (_: Throwable) {}

            // 2. Merged tree substring match
            try {
                val nodes = composeTestRule.onAllNodesWithText(candidate, substring = true)
                    .fetchSemanticsNodes()
                if (nodes.isNotEmpty()) {
                    composeTestRule.onAllNodesWithText(candidate, substring = true)[0]
                        .performClick()
                    composeTestRule.waitForIdle()
                    Thread.sleep(1000)
                    return true
                }
            } catch (_: Throwable) {}

            // 3. Unmerged tree exact text (fallback for deeply nested nodes)
            try {
                val nodes = composeTestRule.onAllNodesWithText(candidate, useUnmergedTree = true)
                    .fetchSemanticsNodes()
                if (nodes.isNotEmpty()) {
                    composeTestRule.onAllNodesWithText(candidate, useUnmergedTree = true)[0]
                        .performClick()
                    composeTestRule.waitForIdle()
                    Thread.sleep(1000)
                    return true
                }
            } catch (_: Throwable) {}

            // 4. Content description match
            try {
                val nodes = composeTestRule.onAllNodesWithContentDescription(candidate, useUnmergedTree = true)
                    .fetchSemanticsNodes()
                if (nodes.isNotEmpty()) {
                    composeTestRule.onAllNodesWithContentDescription(candidate, useUnmergedTree = true)[0]
                        .performClick()
                    composeTestRule.waitForIdle()
                    Thread.sleep(1000)
                    return true
                }
            } catch (_: Throwable) {}
        }
        return false
    }

    /**
     * Write a full-screen screenshot to the device filesystem.
     */
    private fun writeScreenshot(name: String) {
        val file = File(screenshotsDir, "$name.png")
        device.takeScreenshot(file)
        println("[flow-map] Screenshot written: ${file.absolutePath}")
    }

    // --- Screen captures ---

    @Test
    fun testCapture_home() {
        println("📸 [flow-map] Capturing: home")
        launchApp()

        Thread.sleep(5000)
        writeScreenshot("home")
        println("✅ [flow-map] Captured: home")
    }

    @Test
    fun testCapture_messages() {
        println("📸 [flow-map] Capturing: messages")
        launchApp()
        if (!tapElement(listOf("Messages"))) { println("⚠️ [flow-map] tapElement failed: \"Messages\""); return }
        Thread.sleep(2000)
        writeScreenshot("messages")
        println("✅ [flow-map] Captured: messages")
    }

    @Test
    fun testCapture_profile() {
        println("📸 [flow-map] Capturing: profile")
        launchApp()
        if (!tapElement(listOf("Profile"))) { println("⚠️ [flow-map] tapElement failed: \"Profile\""); return }
        Thread.sleep(2000)
        writeScreenshot("profile")
        println("✅ [flow-map] Captured: profile")
    }

    @Test
    fun testCapture_prescriptions2() {
        println("📸 [flow-map] Capturing: prescriptions2")
        launchApp()
        if (!tapElement(listOf("Prescriptions"))) { println("⚠️ [flow-map] tapElement failed: \"Prescriptions\""); return }
        Thread.sleep(2000)
        writeScreenshot("prescriptions2")
        println("✅ [flow-map] Captured: prescriptions2")
    }

    @Test
    fun testCapture_appointments() {
        println("📸 [flow-map] Capturing: appointments")
        launchApp()
        if (!tapElement(listOf("Appointments"))) { println("⚠️ [flow-map] tapElement failed: \"Appointments\""); return }
        Thread.sleep(2000)
        writeScreenshot("appointments")
        println("✅ [flow-map] Captured: appointments")
    }

    @Test
    fun testCapture_archived_messages() {
        println("📸 [flow-map] Capturing: archived_messages")
        launchApp()
        if (!tapElement(listOf("Messages"))) { println("⚠️ [flow-map] tapElement failed: \"Messages\""); return }
        if (!tapElement(listOf("Archived Messages"))) { println("⚠️ [flow-map] tapElement failed: \"Archived Messages\""); return }
        Thread.sleep(2000)
        writeScreenshot("archived_messages")
        println("✅ [flow-map] Captured: archived_messages")
    }

    @Test
    fun testCapture_message_detail() {
        println("📸 [flow-map] Capturing: message_detail")
        launchApp()
        if (!tapElement(listOf("Messages"))) { println("⚠️ [flow-map] tapElement failed: \"Messages\""); return }
        if (!tapElement(listOf("Message Detail"))) { println("⚠️ [flow-map] tapElement failed: \"Message Detail\""); return }
        Thread.sleep(2000)
        writeScreenshot("message_detail")
        println("✅ [flow-map] Captured: message_detail")
    }

    @Test
    fun testCapture_prescriptionStartRepeat() {
        println("📸 [flow-map] Capturing: prescriptionStartRepeat")
        launchApp()
        if (!tapElement(listOf("Prescriptions"))) { println("⚠️ [flow-map] tapElement failed: \"Prescriptions\""); return }
        if (!tapElement(listOf("Request a repeat prescription", "Prescription Start Repeat"))) { println("⚠️ [flow-map] tapElement failed: \"Request a repeat prescription\", \"Prescription Start Repeat\""); return }
        Thread.sleep(2000)
        writeScreenshot("prescriptionStartRepeat")
        println("✅ [flow-map] Captured: prescriptionStartRepeat")
    }

    @Test
    fun testCapture_prescriptionPharmacyDetail() {
        println("📸 [flow-map] Capturing: prescriptionPharmacyDetail")
        launchApp()
        if (!tapElement(listOf("Prescriptions"))) { println("⚠️ [flow-map] tapElement failed: \"Prescriptions\""); return }
        if (!tapElement(listOf("Prescription Pharmacy Detail"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Pharmacy Detail\""); return }
        Thread.sleep(2000)
        writeScreenshot("prescriptionPharmacyDetail")
        println("✅ [flow-map] Captured: prescriptionPharmacyDetail")
    }

    @Test
    fun testCapture_bookAppointmentMenu() {
        println("📸 [flow-map] Capturing: bookAppointmentMenu")
        launchApp()
        if (!tapElement(listOf("Appointments"))) { println("⚠️ [flow-map] tapElement failed: \"Appointments\""); return }
        if (!tapElement(listOf("Book an appointment", "Book Appointment Menu"))) { println("⚠️ [flow-map] tapElement failed: \"Book an appointment\", \"Book Appointment Menu\""); return }
        Thread.sleep(2000)
        writeScreenshot("bookAppointmentMenu")
        println("✅ [flow-map] Captured: bookAppointmentMenu")
    }

    @Test
    fun testCapture_referrals() {
        println("📸 [flow-map] Capturing: referrals")
        launchApp()
        if (!tapElement(listOf("Appointments"))) { println("⚠️ [flow-map] tapElement failed: \"Appointments\""); return }
        if (!tapElement(listOf("Referrals"))) { println("⚠️ [flow-map] tapElement failed: \"Referrals\""); return }
        Thread.sleep(2000)
        writeScreenshot("referrals")
        println("✅ [flow-map] Captured: referrals")
    }

    @Test
    fun testCapture_prescriptionAddPharmacy() {
        println("📸 [flow-map] Capturing: prescriptionAddPharmacy")
        launchApp()
        if (!tapElement(listOf("Prescriptions"))) { println("⚠️ [flow-map] tapElement failed: \"Prescriptions\""); return }
        if (!tapElement(listOf("Request a repeat prescription", "Prescription Start Repeat"))) { println("⚠️ [flow-map] tapElement failed: \"Request a repeat prescription\", \"Prescription Start Repeat\""); return }
        if (!tapElement(listOf("Prescription Add Pharmacy"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Add Pharmacy\""); return }
        Thread.sleep(2000)
        writeScreenshot("prescriptionAddPharmacy")
        println("✅ [flow-map] Captured: prescriptionAddPharmacy")
    }

    @Test
    fun testCapture_askHealthProblemStart() {
        println("📸 [flow-map] Capturing: askHealthProblemStart")
        launchApp()
        if (!tapElement(listOf("Appointments"))) { println("⚠️ [flow-map] tapElement failed: \"Appointments\""); return }
        if (!tapElement(listOf("Book an appointment", "Book Appointment Menu"))) { println("⚠️ [flow-map] tapElement failed: \"Book an appointment\", \"Book Appointment Menu\""); return }
        if (!tapElement(listOf("Ask about a health problem", "Ask Health Problem Start"))) { println("⚠️ [flow-map] tapElement failed: \"Ask about a health problem\", \"Ask Health Problem Start\""); return }
        Thread.sleep(2000)
        writeScreenshot("askHealthProblemStart")
        println("✅ [flow-map] Captured: askHealthProblemStart")
    }

    @Test
    fun testCapture_bookAppointmentStart() {
        println("📸 [flow-map] Capturing: bookAppointmentStart")
        launchApp()
        if (!tapElement(listOf("Appointments"))) { println("⚠️ [flow-map] tapElement failed: \"Appointments\""); return }
        if (!tapElement(listOf("Book an appointment", "Book Appointment Menu"))) { println("⚠️ [flow-map] tapElement failed: \"Book an appointment\", \"Book Appointment Menu\""); return }
        if (!tapElement(listOf("Check for available GP appointments", "Book Appointment Start"))) { println("⚠️ [flow-map] tapElement failed: \"Check for available GP appointments\", \"Book Appointment Start\""); return }
        Thread.sleep(2000)
        writeScreenshot("bookAppointmentStart")
        println("✅ [flow-map] Captured: bookAppointmentStart")
    }

    @Test
    fun testCapture_noAppointmentsAvailable() {
        println("📸 [flow-map] Capturing: noAppointmentsAvailable")
        launchApp()
        if (!tapElement(listOf("Appointments"))) { println("⚠️ [flow-map] tapElement failed: \"Appointments\""); return }
        if (!tapElement(listOf("Book an appointment", "Book Appointment Menu"))) { println("⚠️ [flow-map] tapElement failed: \"Book an appointment\", \"Book Appointment Menu\""); return }
        if (!tapElement(listOf("Check for available GP appointments", "No Appointments Available"))) { println("⚠️ [flow-map] tapElement failed: \"Check for available GP appointments\", \"No Appointments Available\""); return }
        Thread.sleep(2000)
        writeScreenshot("noAppointmentsAvailable")
        println("✅ [flow-map] Captured: noAppointmentsAvailable")
    }

    @Test
    fun testCapture_prescriptionMedicineDetail() {
        println("📸 [flow-map] Capturing: prescriptionMedicineDetail")
        launchApp()
        if (!tapElement(listOf("Prescriptions"))) { println("⚠️ [flow-map] tapElement failed: \"Prescriptions\""); return }
        if (!tapElement(listOf("Request a repeat prescription", "Prescription Start Repeat"))) { println("⚠️ [flow-map] tapElement failed: \"Request a repeat prescription\", \"Prescription Start Repeat\""); return }
        if (!tapElement(listOf("Prescription Add Pharmacy"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Add Pharmacy\""); return }
        if (!tapElement(listOf("Prescription Medicine Detail"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Medicine Detail\""); return }
        Thread.sleep(2000)
        writeScreenshot("prescriptionMedicineDetail")
        println("✅ [flow-map] Captured: prescriptionMedicineDetail")
    }

    @Test
    fun testCapture_prescriptionAdditionalDetail() {
        println("📸 [flow-map] Capturing: prescriptionAdditionalDetail")
        launchApp()
        if (!tapElement(listOf("Prescriptions"))) { println("⚠️ [flow-map] tapElement failed: \"Prescriptions\""); return }
        if (!tapElement(listOf("Request a repeat prescription", "Prescription Start Repeat"))) { println("⚠️ [flow-map] tapElement failed: \"Request a repeat prescription\", \"Prescription Start Repeat\""); return }
        if (!tapElement(listOf("Prescription Add Pharmacy"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Add Pharmacy\""); return }
        if (!tapElement(listOf("Prescription Medicine Detail"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Medicine Detail\""); return }
        if (!tapElement(listOf("Prescription Additional Detail"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Additional Detail\""); return }
        Thread.sleep(2000)
        writeScreenshot("prescriptionAdditionalDetail")
        println("✅ [flow-map] Captured: prescriptionAdditionalDetail")
    }

    @Test
    fun testCapture_prescriptionFormRepeat() {
        println("📸 [flow-map] Capturing: prescriptionFormRepeat")
        launchApp()
        if (!tapElement(listOf("Prescriptions"))) { println("⚠️ [flow-map] tapElement failed: \"Prescriptions\""); return }
        if (!tapElement(listOf("Request a repeat prescription", "Prescription Start Repeat"))) { println("⚠️ [flow-map] tapElement failed: \"Request a repeat prescription\", \"Prescription Start Repeat\""); return }
        if (!tapElement(listOf("Prescription Add Pharmacy"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Add Pharmacy\""); return }
        if (!tapElement(listOf("Prescription Medicine Detail"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Medicine Detail\""); return }
        if (!tapElement(listOf("Prescription Additional Detail"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Additional Detail\""); return }
        if (!tapElement(listOf("Prescription Form Repeat"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Form Repeat\""); return }
        Thread.sleep(2000)
        writeScreenshot("prescriptionFormRepeat")
        println("✅ [flow-map] Captured: prescriptionFormRepeat")
    }

    @Test
    fun testCapture_prescriptionConfirmationRepeat() {
        println("📸 [flow-map] Capturing: prescriptionConfirmationRepeat")
        launchApp()
        if (!tapElement(listOf("Prescriptions"))) { println("⚠️ [flow-map] tapElement failed: \"Prescriptions\""); return }
        if (!tapElement(listOf("Request a repeat prescription", "Prescription Start Repeat"))) { println("⚠️ [flow-map] tapElement failed: \"Request a repeat prescription\", \"Prescription Start Repeat\""); return }
        if (!tapElement(listOf("Prescription Add Pharmacy"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Add Pharmacy\""); return }
        if (!tapElement(listOf("Prescription Medicine Detail"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Medicine Detail\""); return }
        if (!tapElement(listOf("Prescription Additional Detail"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Additional Detail\""); return }
        if (!tapElement(listOf("Prescription Form Repeat"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Form Repeat\""); return }
        if (!tapElement(listOf("Prescription Confirmation Repeat"))) { println("⚠️ [flow-map] tapElement failed: \"Prescription Confirmation Repeat\""); return }
        Thread.sleep(2000)
        writeScreenshot("prescriptionConfirmationRepeat")
        println("✅ [flow-map] Captured: prescriptionConfirmationRepeat")
    }
}
